name: Validate Pull Request

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate PR
        run: scripts/validate-pr.sh
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Check for issue number
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^KEYCLOAK-\d{1,5}\s.*'
          error: 'Commit messasge title must be prefixed with KEYCLOAK-Issue followed by a space, e.g.: KEYCLOAK-12345 My message'
          excludeTitle: 'false' # optional: this excludes the title of a pull request
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request

      - name: Check Line Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^.{1,90}$'
          error: 'The maximum line length of 90 characters is exceeded.'
          excludeTitle: 'false' # optional: this excludes the title of a pull request
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
#          checkAllCommitMessages: 'false' # optional: this checks all commits associated with a pull request
#          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true

#      - name: Check for Resolves / Fixes
#        uses: gsactions/commit-message-checker@v1
#        with:
#          pattern: '^.+(Resolves|Fixes): \#[0-9]+$'
#          error: 'You need at least one "Resolves|Fixes: #<issue number>" line.'